from parser import GOAL_LIST,GLOBAL_MAP
width=len(GLOBAL_MAP[0])
BOX_LEGAL=list()
BOX_LEGAL.append([False for i in range(width)])
for i in range(1,len(GLOBAL_MAP)-1):
    BOX_LEGAL.append([False])
    for j in range(1,width-1):
        if(not GLOBAL_MAP[i][j]):
            BOX_LEGAL[i].append(False)
            continue
        left_up=not (GLOBAL_MAP[i-1][j] or GLOBAL_MAP[i][j-1]) #demorgan lol
        left_down=not (GLOBAL_MAP[i-1][j] or GLOBAL_MAP[i][j+1])
        right_up=not (GLOBAL_MAP[i+1][j] or GLOBAL_MAP[i][j-1])
        right_down=not (GLOBAL_MAP[i+1][j] or GLOBAL_MAP[i][j+1])
        BOX_LEGAL[i].append(not( left_up or left_down or right_down or right_up) or [i,j] in GOAL_LIST)
    BOX_LEGAL[i].append(False)
BOX_LEGAL.append([False for i in range(width)])

MOVE_SET=((-1,0),(0,1),(1,0),(0,-1))
class entity:
    def __init__(self, y:int, x:int):
        self.y=y
        self.x=x
    # clockwise moving pattern
    # 0 up, 1 right 2 bottom 3 left
    def targetPos(self, move: int) -> tuple:
        target_y=self.y + MOVE_SET[move][0]
        target_x=self.x + MOVE_SET[move][1]
        return [target_y,target_x]
    
    def clearFront(self, move: int, box_map: list) -> bool:
        target=self.targetPos(move)
        y_pos=target[0]
        x_pos=target[1]
        if y_pos>=len(GLOBAL_MAP) or x_pos>=len(GLOBAL_MAP[0]):
            return False
        if GLOBAL_MAP[target[0]][target[1]] and (target not in box_map):
            return True
        return False


    def pos(self):
        return [self.y,self.x]
    
    def __eq__(self, value):
        return self.pos() == value

    def _boxInFront(self, move: int, box_map: list):
        
        return self.targetPos(move) in box_map
    
    def _fetchBox(self, position: tuple, box_map: list)-> box:
        for i in range(len(box_map)):
            if box_map[i]==position:
                return box_map[i]
            
    # def _inverseMove(self,move):
    #     if move==0:
    #         return 2
    #     elif move==1:
    #         return 3
    #     elif move==2:
    #         return 0
    #     elif move==3:
    #         return 1

class box(entity):
    def __init__(self, y, x):
        super().__init__(y, x)
        self.on_goal=self.onGoal()

    #can make a legal move as is
    #decided not to go into too much depth and just check in a depth of 0 if it could move as is now
    #just not the best position
    # def boxSoftStuck(self,box_map:list,):
    #     moves=[0,0]
    #     if self.on_goal:
    #         return False
    #     for i in range(4):
    #         if not self.canMove(i,box_map):
    #             moves[i%2]+=1
    #     # if moves[0]>0 and moves[1]>0:
    #     #     print(self.pos())
    #     return moves[0]>0 and moves[1]>0
    
    def clearFront(self, move: int, box_map: list) -> bool:
        target=self.targetPos(move)
        y_pos=target[0]
        x_pos=target[1]
        if y_pos>=len(BOX_LEGAL) or x_pos>=len(BOX_LEGAL[0]):
            return False
        if BOX_LEGAL[target[0]][target[1]] and (target not in box_map):
            return True
        return False


    def canMove(self, move: int, box_map: list) -> int:
        # gotta move it move it
        if self.clearFront(move,box_map): #and self.clearFront(self._inverseMove(move),box_map):
            return 1
        # stuck for said move
        return 0
    
    def move(self, move: int, box_map: list) -> None:
        if self.canMove(move, box_map)==1:
            self.y+=MOVE_SET[move][0]
            self.x+=MOVE_SET[move][1]
            self.on_goal=self.onGoal()

    # this is generated by gpt, my method is the one from bellow but its too slow
    def boxStuck(self, box_map):
        if self.on_goal:
            return False

        # Normalize boxes to a set of (y, x) for O(1) membership checks
        box_set = set()
        for b in box_map:
            if isinstance(b, (list, tuple)) and len(b) >= 2:
                box_set.add((b[0], b[1]))
            else:
                # supports objects with .y/.x too
                box_set.add((b.y, b.x))

        y = self.y
        x = self.x
        gm = GLOBAL_MAP  # local ref for speed

        ym1, y0, yp1 = y - 1, y, y + 1
        xm1, x0, xp1 = x - 1, x, x + 1

        row_ym1 = gm[ym1]
        row_y0  = gm[y0]
        row_yp1 = gm[yp1]

        # Same predicate as your original: box present OR NOT wall-flag
        a00 = ((ym1, xm1) in box_set) or (not row_ym1[xm1])
        a01 = ((ym1, x0 ) in box_set) or (not row_ym1[x0 ])
        a02 = ((ym1, xp1) in box_set) or (not row_ym1[xp1])

        a10 = ((y0 , xm1) in box_set) or (not row_y0 [xm1])
        a11 = ((y0 , x0 ) in box_set) or (not row_y0 [x0 ])
        a12 = ((y0 , xp1) in box_set) or (not row_y0 [xp1])

        a20 = ((yp1, xm1) in box_set) or (not row_yp1[xm1])
        a21 = ((yp1, x0 ) in box_set) or (not row_yp1[x0 ])
        a22 = ((yp1, xp1) in box_set) or (not row_yp1[xp1])

        # Any fully-true 2x2 block?
        if (a00 and a01 and a10 and a11): return True
        if (a01 and a02 and a11 and a12): return True
        if (a10 and a11 and a20 and a21): return True
        if (a11 and a12 and a21 and a22): return True
        return False

    
    # 10-20% faster thn OG , still gpt much faster
    # def boxStuck(self, box_map):
    #     if self.on_goal:
    #         return False
    #     grid=list()
    #     for i in [-1,0,1]:
    #         grid.append([([self.y+i,self.x+j] in box_map) or not (GLOBAL_MAP[self.y+i][self.x+j]) for j in [-1,0,1]])

    #     res=False
    #     for i in range(2):
    #         for j in range(2):
    #             res=res or (grid[i][j] and grid[i][j+1] and grid[i+1][j] and grid[i+1][j+1])
    #     return res
    
    # slow
    # # def boxStuck(self, box_map):
    #     if self.on_goal:
    #         return False
    #     grid_box=[
    #             [],
    #             [],
    #             []]
    #     for i in [-1,0,1]:
    #         for j in [-1,0,1]:
    #             grid_box[i+1].append([self.y+i,self.x+j] in box_map)
    #     grid_wall=[
    #             [],
    #             [],
    #             []]
    #     for i in [-1,0,1]:
    #         for j in [-1,0,1]:
    #             grid_wall[i+1].append(GLOBAL_MAP[self.y+i][self.x+j])
    #     final_grid=[
    #             [],
    #             [],
    #             []]
    #     for i in range(3):
    #         for j in range(3):
    #             final_grid[i].append(grid_box[i][j] or not grid_wall[i][j])

    #     for i in range(2):
    #         for j in range(2):
    #             if final_grid[i][j] and final_grid[i][j+1] and final_grid[i+1][j] and final_grid[i+1][j+1]:
    #                 return True
    #     return False
    #shi is done

    def onGoal(self) -> bool:
        return self.pos() in GOAL_LIST

class player(entity):
        def __init__(self, y: int, x: int, box_map: list):
            super().__init__(y, x)
            self.boxes=box_map
        
        def _boxInFront(self, move):
            return super()._boxInFront(move, self.boxes)
        
        def _fetchBox(self, position):
            return super()._fetchBox(position, self.boxes)
        
        # 0 no, -1 moves box , 1 can move
        def canMove(self, move: int,  box_map: list) -> int:
            if self.clearFront(move,box_map):
                return 1
            if not self._boxInFront(move):
                return 0    
            target=self.targetPos(move)
            front_box=self._fetchBox(target)
            if front_box.canMove(move,box_map)==1:
                return -1
            return 0

        def move(self, move: int,box_map: list) -> None:
            target=self.targetPos(move)
            move_result=self.canMove(move,box_map)
            if move_result == 0:
                return None
            if move_result==-1:
                target_box=self._fetchBox(target)
                target_box.move(move,box_map)
            self.y=target[0]
            self.x=target[1]
            
            

